# Copyright 2026 sshpier contributors
# SPDX-License-Identifier: Apache-2.0
"""End-to-end tests for pull / deploy / rollback against a local fake server."""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

from sshpier import sync
from sshpier.sync import Git, Site
from sshpier.transport import LocalTransport


@pytest.fixture(autouse=True)
def _git_identity(monkeypatch):
    monkeypatch.setenv("GIT_AUTHOR_NAME", "test")
    monkeypatch.setenv("GIT_AUTHOR_EMAIL", "test@example.invalid")
    monkeypatch.setenv("GIT_COMMITTER_NAME", "test")
    monkeypatch.setenv("GIT_COMMITTER_EMAIL", "test@example.invalid")


def _has_git() -> bool:
    try:
        subprocess.run(["git", "--version"], capture_output=True, check=True)
        return True
    except (OSError, subprocess.CalledProcessError):  # pragma: no cover
        return False


pytestmark = pytest.mark.skipif(not _has_git(), reason="git not available")


@pytest.fixture
def server(tmp_path):
    """A directory that stands in for the remote machine."""
    root = tmp_path / "server"
    web = root / "srv" / "www"
    web.mkdir(parents=True)
    (web / "index.html").write_text("<h1>original</h1>\n")
    (web / "style.css").write_text("body{}\n")
    sub = web / "inc"
    sub.mkdir()
    (sub / "header.php").write_text("<?php // header\n")
    # data that must never be pulled
    data = web / "uploads"
    data.mkdir()
    (data / "big.bin").write_bytes(b"x" * 4096)
    return root


@pytest.fixture
def site():
    return Site(name="demo", host="localhost", remote="/srv/www",
                backup="/srv/backup", exclude=("uploads/", "*.log"))


@pytest.fixture
def tr(server):
    return LocalTransport(server)


@pytest.fixture
def work(tmp_path):
    return tmp_path / "work" / "demo"


# --------------------------------------------------------------------------


def test_pull_collects_and_commits(tr, site, work):
    result = sync.pull(tr, site, work)

    assert (work / "index.html").read_text() == "<h1>original</h1>\n"
    assert (work / "inc" / "header.php").exists()
    assert result["changed"] is True
    assert Git(work).has_commits()


def test_pull_honours_exclude(tr, site, work):
    sync.pull(tr, site, work)
    assert not (work / "uploads").exists(), "excluded directory was pulled"


def test_pull_twice_is_a_no_op(tr, site, work):
    sync.pull(tr, site, work)
    second = sync.pull(tr, site, work)
    assert second["changed"] is False


def test_pull_notices_server_side_edits(tr, site, work, server):
    sync.pull(tr, site, work)
    (server / "srv" / "www" / "index.html").write_text("<h1>edited on server</h1>\n")
    result = sync.pull(tr, site, work)
    assert result["changed"] is True
    assert (work / "index.html").read_text() == "<h1>edited on server</h1>\n"


def test_deploy_sends_only_changed_files(tr, site, work, server):
    sync.pull(tr, site, work)
    git = Git(work)
    git.tag("deploy/base")

    (work / "index.html").write_text("<h1>new</h1>\n")
    git.commit_all("edit index")

    result = sync.deploy(tr, site, work, tag="deploy/001", since="deploy/base")

    assert result["files"] == ["index.html"]
    assert (server / "srv" / "www" / "index.html").read_text() == "<h1>new</h1>\n"
    # untouched file left alone
    assert (server / "srv" / "www" / "style.css").read_text() == "body{}\n"


def test_deploy_does_not_delete_server_created_files(tr, site, work, server):
    """Files the application made must survive a deployment."""
    sync.pull(tr, site, work)
    Git(work).tag("deploy/base")

    runtime = server / "srv" / "www" / "runtime-cache.txt"
    runtime.write_text("generated by the app\n")

    (work / "index.html").write_text("<h1>v2</h1>\n")
    Git(work).commit_all("edit")
    sync.deploy(tr, site, work, tag="deploy/002", since="deploy/base")

    assert runtime.exists(), "deployment removed a file created on the server"


def test_deploy_refuses_when_server_drifted(tr, site, work, server):
    sync.pull(tr, site, work)
    Git(work).tag("deploy/base")

    (work / "index.html").write_text("<h1>mine</h1>\n")
    Git(work).commit_all("mine")
    sync.deploy(tr, site, work, tag="deploy/003", since="deploy/base")

    # somebody edits the server directly, outside this tool
    (server / "srv" / "www" / "index.html").write_text("<h1>theirs</h1>\n")

    (work / "index.html").write_text("<h1>mine again</h1>\n")
    Git(work).commit_all("mine again")

    with pytest.raises(RuntimeError) as exc:
        sync.deploy(tr, site, work, tag="deploy/004", since="deploy/003")
    assert "index.html" in str(exc.value)

    # their change is still there — we did not clobber it
    assert (server / "srv" / "www" / "index.html").read_text() == "<h1>theirs</h1>\n"


def test_deploy_force_overrides_drift_check(tr, site, work, server):
    sync.pull(tr, site, work)
    Git(work).tag("deploy/base")
    (work / "index.html").write_text("<h1>a</h1>\n")
    Git(work).commit_all("a")
    sync.deploy(tr, site, work, tag="deploy/005", since="deploy/base")

    (server / "srv" / "www" / "index.html").write_text("<h1>drift</h1>\n")
    (work / "index.html").write_text("<h1>b</h1>\n")
    Git(work).commit_all("b")

    sync.deploy(tr, site, work, tag="deploy/006", since="deploy/005", force=True)
    assert (server / "srv" / "www" / "index.html").read_text() == "<h1>b</h1>\n"


def test_deploy_refuses_dirty_tree(tr, site, work):
    sync.pull(tr, site, work)
    (work / "index.html").write_text("uncommitted\n")
    with pytest.raises(RuntimeError):
        sync.deploy(tr, site, work, tag="deploy/007")


def test_rollback_restores_previous_content(tr, site, work, server):
    sync.pull(tr, site, work)
    Git(work).tag("deploy/base")

    (work / "index.html").write_text("<h1>broken release</h1>\n")
    Git(work).commit_all("break it")
    sync.deploy(tr, site, work, tag="deploy/008", since="deploy/base")
    assert (server / "srv" / "www" / "index.html").read_text() == "<h1>broken release</h1>\n"

    result = sync.rollback(tr, site, work, tag="deploy/008")

    assert result["restored"] >= 1
    assert (server / "srv" / "www" / "index.html").read_text() == "<h1>original</h1>\n"


def test_deploy_with_nothing_changed(tr, site, work):
    sync.pull(tr, site, work)
    Git(work).tag("deploy/base")
    result = sync.deploy(tr, site, work, tag="deploy/009", since="deploy/base")
    assert result["deployed"] == 0


def test_status_reports_drift_and_pending(tr, site, work, server):
    sync.pull(tr, site, work)
    Git(work).tag("deploy/base")
    (work / "index.html").write_text("<h1>x</h1>\n")
    Git(work).commit_all("x")
    sync.deploy(tr, site, work, tag="deploy/010", since="deploy/base")

    state = sync.status(tr, site, work)
    assert state["clean"] is True

    (server / "srv" / "www" / "index.html").write_text("<h1>touched</h1>\n")
    (work / "style.css").write_text("body{color:red}\n")
    Git(work).commit_all("style")

    state = sync.status(tr, site, work)
    assert "index.html" in state["drift"]
    assert "style.css" in state["pending"]
    assert state["clean"] is False


def test_extract_rejects_path_traversal(tmp_path):
    import tarfile

    archive = tmp_path / "evil.tgz"
    victim = tmp_path / "payload"
    victim.write_text("nope")
    with tarfile.open(archive, "w:gz") as tar:
        tar.add(victim, arcname="../escaped.txt")

    target = tmp_path / "out"
    target.mkdir()
    with pytest.raises(RuntimeError):
        sync._safe_extract(archive, target)
